### ISSUE TITLE
Feature request - Add a .csv log file to Splunk SIEM for Insider Threat

### ISSUE THREAD

**Issue by aviditas-security** [blueteamvillage/DC31-obsidian-sec-eng#122]
# Background:
For an Insider Threat kc, would like to have a log file uploaded to the Splunk instance. This will be crafted data that I will test with Splunk ahead of time to ensure that it auto-parses. I'll be setting the timestamps in the logs to match the KC activity timeframes so there is no need for it to happen concurrently unless that is best from a SecEng perspective.
I would prefer that this happens after the KC as I would have better data to match to then. 

# Request for us to build
Add a .csv file to Splunk, pretty please. 

# CRITERIA FOR SUCCESS
Upload a provided .csv file to Splunk
Use the auto-parse in the upload process 
Confirm that the logs are in Splunk

# DRIs
aviditas-security a.skye (aviditas)#6832

**Comment by juju4** [comment]
Closing. capability there but in the end, not used for this year. Defcon 31 ended.
